//! Plain data types that cross crate boundaries. Depends only on `serde`,
//! so it sits below both the provider and the store without creating a
//! dependency cycle.

use serde::Serialize;

/// A usage record extracted from an upstream response.
#[derive(Debug, Default, Clone)]
pub struct Usage {
    /// Model that handled the request, or `"unknown"` when unavailable.
    pub model: String,
    /// Proxy endpoint through which the request was made.
    pub endpoint: String,
    /// Number of input tokens processed, including cached tokens.
    pub input_tokens: i64,
    /// Number of tokens generated by the model.
    pub output_tokens: i64,
    /// Tokens served from the KV cache (prefilled).
    pub cached_tokens: i64,
    /// Total number of input and output tokens reported for the request.
    pub total_tokens: i64,
    /// `None` for keyless requests.
    pub api_key_id: Option<i64>,
}

/// Aggregated usage for one model.
#[derive(Debug, Serialize)]
pub struct ModelStats {
    /// Model represented by this aggregate.
    pub model: String,
    /// Number of requests included in the aggregate.
    pub requests: i64,
    /// Total input tokens processed.
    pub input_tokens: i64,
    /// Total output tokens generated.
    pub output_tokens: i64,
    /// Total input tokens served from a cache.
    pub cached_tokens: i64,
    /// Total tokens processed and generated.
    pub total_tokens: i64,
}

/// One row of a per-account breakdown: a per-user aggregate in the admin
/// view (`stats_by_user`) or a single key in the per-user view
/// (`stats_by_key_for_user`).
#[derive(Debug, Serialize)]
pub struct KeyStats {
    /// `None` for per-user aggregates and keyless requests.
    pub api_key_id: Option<i64>,
    /// Username or key name/prefix; `"GENERIC"` for keyless,
    /// `"(deleted key #id)"` for dangling references.
    pub label: String,
    /// Number of requests included in the aggregate.
    pub requests: i64,
    /// Total input tokens processed.
    pub input_tokens: i64,
    /// Total output tokens generated.
    pub output_tokens: i64,
    /// Total input tokens served from a cache.
    pub cached_tokens: i64,
    /// Total tokens processed and generated.
    pub total_tokens: i64,
}

/// One day/model bucket for the time-series chart.
#[derive(Debug, Serialize)]
pub struct DailyStats {
    /// `YYYY-MM-DD`, local timezone.
    pub day: String,
    /// Model represented by this bucket.
    pub model: String,
    /// Number of requests made during the day.
    pub requests: i64,
    /// Total input tokens processed during the day.
    pub input_tokens: i64,
    /// Total output tokens generated during the day.
    pub output_tokens: i64,
    /// Total input tokens served from a cache during the day.
    pub cached_tokens: i64,
    /// Total tokens processed and generated during the day.
    pub total_tokens: i64,
}

/// Elapsed call time and GPU power draw for one busy interval.
#[derive(Debug, Default, Clone)]
pub struct EnergyRecord {
    /// Duration of the measured busy interval, in seconds.
    pub elapsed_secs: f64,
    /// GPU power draw during the interval, in watts.
    pub gpu_watts: f64,
}

/// One day of aggregated energy. The kWh is
/// `SUM(elapsed_secs * gpu_watts) / 3_600_000.0` (watt-seconds to kWh).
#[derive(Debug, Serialize)]
pub struct DailyEnergy {
    /// `YYYY-MM-DD`, local timezone.
    pub day: String,
    /// Energy consumed during the day, in kilowatt-hours.
    pub kwh: f64,
}

/// One five-minute bucket for the current day. The day is always split into
/// exactly 288 buckets so the dashboard can render a fixed-width chart.
#[derive(Debug, Serialize, Clone)]
pub struct TodayBucket {
    /// 0..287; 0 is midnight local time.
    pub bucket: u16,
    /// Total input tokens processed during the interval.
    pub input_tokens: i64,
    /// Total output tokens generated during the interval.
    pub output_tokens: i64,
    /// Total input tokens served from a cache during the interval.
    pub cached_tokens: i64,
    /// Number of requests made during the interval.
    pub requests: i64,
}
