name: Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: build & test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master (toolchain 1.88.0)
        with:
          toolchain: 1.88.0
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: rustfmt
        run: cargo fmt --all --check
      - name: clippy
        run: cargo clippy --workspace --all-targets --locked -- -D warnings
      - name: test
        run: cargo test --workspace --locked

  audit:
    name: cargo audit
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUSTUP_TOOLCHAIN: stable
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master (toolchain stable)
        with:
          toolchain: stable
      - uses: taiki-e/install-action@2ca9b94c269419b7b0c711c09d0b21c4e1d51145 # v2
        with:
          tool: cargo-audit
      - name: audit
        run: cargo audit
